### ISSUE TITLE
Support mobile ( and smaller screens in general)

### ISSUE THREAD

**Issue by svienot** [hashgraph/hedera-mirror-node-explorer#1]
- [x] hashgraph/hedera-mirror-node-explorer#19 
- [x] hashgraph/hedera-mirror-node-explorer#3 
- [x] hashgraph/hedera-mirror-node-explorer#5 
- [x] hashgraph/hedera-mirror-node-explorer#4

**Comment by svienot** [comment]
Closing this as Hashscan is now 'officially' available on mobile.
There is still room for improvement, which will be addressed with ad-hoc issues.
