### ISSUE TITLE
Hashscan UI redesign and light/dark mode 

### ISSUE THREAD

**Issue by AliNik4n** [hashgraph/hedera-mirror-node-explorer#1515]
### Problem

Current UI design can be improved to provide a better experience for users 

### Solution

- Update the current UI to enhance user experience 
- Add light / dark mode 

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-mirror-node-explorer/issues/1551
- [ ] https://github.com/hashgraph/hedera-mirror-node-explorer/issues/1558
- [ ] Migrate code to Bulma 1.0.2
- [ ] Migrate code to Oruga 0.9.2
- [ ] https://github.com/hashgraph/hedera-mirror-node-explorer/issues/1577
```

**Comment by FleebsSS** [comment]
If I may add a comment, is that there are many current issues with the Hashscan functionality and UI. My suggestion is simply to adopt an **Etherscan type explorer** which has been battletested and upgraded over many years (and continues to do so) to iron out all the typical issues and provide a very user friendly experience. Some issues include not being able to see top holders of a token, not being able to filter transactions of a holder by token type, no private tags, no hyperlink functionaility for txs. etc. etc I could go on, my point is that attempting to identify each of these issues and solve 1 by 1 could be a large waste of time and resources, especially when a great product already exists with all these issues already being solved. Another benefit of an etherscan type explorer is that the majorty of web3 is familiar with that interface and so it would help bring familiarlity to the Hedera space and be less of a hinderance to onboard more web3 users.
