### ISSUE TITLE
Implement updated designs across the tabs 

### ISSUE THREAD

**Issue by SimiHunjan** [hashgraph/hedera-mirror-node-explorer#787]
### Problem

The smart contract UI designs provide changes that were specific to the smart contract flow. Some of those changes can be applied to other areas in the site. We need to identify which changes need to be pulled in the experience across all pages. For example, the expandable design can be applied to other tabs like tokens, transactions, accounts, etc.

### Solution

Review the changes that need to be applied more globally to keep a consistent experience. 

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-mirror-node-explorer/issues/822
- [ ] https://github.com/hashgraph/hedera-mirror-node-explorer/issues/871
- [ ] https://github.com/hashgraph/hedera-mirror-node-explorer/issues/884
- [ ] https://github.com/hashgraph/hedera-mirror-node-explorer/issues/826
- [ ] https://github.com/hashgraph/hedera-mirror-node-explorer/issues/901
```
```[tasklist]
### Tasks
```
